declare module 'lucide-react' {
    import { FC, SVGProps } from 'react';

    export interface LucideProps extends Partial<Omit<SVGProps<SVGSVGElement>, 'ref'>> {
        size?: string | number;
        absoluteStrokeWidth?: boolean;
        strokeWidth?: string | number;
    }

    export type LucideIcon = FC<LucideProps>;

    // Common icons used across the project
    export const Mail: LucideIcon;
    export const Phone: LucideIcon;
    export const Linkedin: LucideIcon;
    export const MapPin: LucideIcon;
    export const Globe: LucideIcon;
    export const Github: LucideIcon;
    export const Briefcase: LucideIcon;
    export const GraduationCap: LucideIcon;
    export const Star: LucideIcon;
    export const Award: LucideIcon;
    export const User: LucideIcon;
    export const Loader: LucideIcon;
    export const Loader2: LucideIcon;
    export const Sparkles: LucideIcon;
    export const ArrowLeft: LucideIcon;
    export const ArrowRight: LucideIcon;
    export const ArrowUpRight: LucideIcon;
    export const ArrowDownRight: LucideIcon;
    export const Upload: LucideIcon;
    export const X: LucideIcon;
    export const XCircle: LucideIcon;
    export const Download: LucideIcon;
    export const Heart: LucideIcon;
    export const MessageCircle: LucideIcon;
    export const Share2: LucideIcon;
    export const Edit: LucideIcon;
    export const Trash2: LucideIcon;
    export const Facebook: LucideIcon;
    export const Instagram: LucideIcon;
    export const Camera: LucideIcon;
    export const Copy: LucideIcon;
    export const Clipboard: LucideIcon;
    export const Check: LucideIcon;
    export const CheckCircle: LucideIcon;
    export const CheckCircle2: LucideIcon;
    export const ChevronLeft: LucideIcon;
    export const ChevronRight: LucideIcon;
    export const ChevronDown: LucideIcon;
    export const ChevronUp: LucideIcon;
    export const ChevronDownUp: LucideIcon;
    export const ChevronDownUpAlt: LucideIcon;
    export const ChevronDownSmall: LucideIcon;
    export const ChevronRightSmall: LucideIcon;
    export const Circle: LucideIcon;
    export const PanelLeft: LucideIcon;
    export const ChevronsUpDown: LucideIcon;
    export const Eye: LucideIcon;
    export const EyeOff: LucideIcon;
    export const Moon: LucideIcon;
    export const Sun: LucideIcon;
    export const Save: LucideIcon;
    export const Plus: LucideIcon;
    export const ToggleLeft: LucideIcon;
    export const ToggleRight: LucideIcon;
    export const Tag: LucideIcon;
    export const Users: LucideIcon;
    export const ShoppingCart: LucideIcon;
    export const LayoutDashboard: LucideIcon;
    export const FileText: LucideIcon;
    export const Bookmark: LucideIcon;
    export const Wallet: LucideIcon;
    export const Package: LucideIcon;
    export const Settings: LucideIcon;
    export const CreditCard: LucideIcon;
    export const DollarSign: LucideIcon;
    export const Banknote: LucideIcon;
    export const Search: LucideIcon;
    export const Laptop: LucideIcon;
    export const BarChart: LucideIcon;
    export const LoaderIcon: LucideIcon;
    export const AlertCircle: LucideIcon;
    export const Lock: LucideIcon;
    export const Bell: LucideIcon;
    export const Shield: LucideIcon;
    export const ShieldCheck: LucideIcon;
    export const Bot: LucideIcon;
    export const Users2: LucideIcon;
    export const Menu: LucideIcon;
    export const Unlock: LucideIcon;
    export const Smile: LucideIcon;
    export const Send: LucideIcon;
    export const Target: LucideIcon;
    export const Zap: LucideIcon;
    export const MessageSquare: LucideIcon;
    export const Languages: LucideIcon;
    export const ArrowLeftRight: LucideIcon;
    export const Calendar: LucideIcon;
    export const Building2: LucideIcon;
    export const Minimize2: LucideIcon;
    export const Maximize2: LucideIcon;
    export const ShoppingBag: LucideIcon;
    export const BarChart3: LucideIcon;
    export const UserCheck: LucideIcon;
    export const Code: LucideIcon;
    export const Info: LucideIcon;
    export const Building: LucideIcon;
    export const Filter: LucideIcon;
    export const RefreshCw: LucideIcon;
    export const MoreVertical: LucideIcon;
    export const TrendingUp: LucideIcon;
    export const PlusCircle: LucideIcon;
    export const UserPlus: LucideIcon;
    export const UserCog: LucideIcon;

    // Fallback for unexpected icons: allow an 'any' named export (permissive)
    export const any: LucideIcon;
}
